### ISSUE TITLE
Increase control of activities import

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#1497]
## Current User Flow

In the current user flow, the file is selected and imported directly.

![import-before-01](https://user-images.githubusercontent.com/4159106/205511795-083cb12c-c7cf-47fd-b707-23c919798976.png)
![import-before-02](https://user-images.githubusercontent.com/4159106/205511798-f4994ad7-79cd-4be4-8647-9c885e087713.png)

## New User Flow

In the new user flow, the file is selected (as before).
![import-after-01](https://user-images.githubusercontent.com/4159106/205511829-31651ffc-c28f-4860-a8bd-10e0f6d22096.png)

Then the activities are presented in a new intermediate step where the user can select the activities to import.

![import-after-02](https://user-images.githubusercontent.com/4159106/205511832-53fe6b15-3bd1-4b8d-a63c-c55a2698a3e5.png)
![import-after-03](https://user-images.githubusercontent.com/4159106/205511838-2d4c09b3-bb38-4842-8b51-5c343c25a817.png)

The new intermediate step will provide further possibilities like displaying validation details in the future to increase the control of the activities import.

## Tasks

- [ ] Extend `ActivitiesTableComponent` with an input parameter to enable checkboxes
- [ ] Extend `ActivitiesTableComponent` with an output parameter to get notified about checked activities
- [ ] Extend `ImportActivitiesDialog` with a second step
- [ ] Integration

**Comment by yksolanki9** [comment]
@dtslvr I'd like to work on this. Please assign this to me.
