### ISSUE TITLE
Extend Dividend / Investment Timeline with group by year option

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#1546]
<img width="1144" alt="dividend-timeline-yearly" src="https://user-images.githubusercontent.com/4159106/209640932-40b36792-aa5e-47e1-a1bb-0a616086658f.png">

<img width="1144" alt="investment-timeline-yearly" src="https://user-images.githubusercontent.com/4159106/209640950-154dabed-7f08-478d-a00b-ce92c9fddd0d.png">

## Tasks

- [ ] Extend [toggle](https://github.com/ghostfolio/ghostfolio/blob/main/apps/client/src/app/pages/portfolio/analysis/analysis-page.component.ts#L48) with _Yearly_ mode
- [ ] Support group by year in [dividend API service](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/app/portfolio/portfolio.service.ts#L211)
- [ ] Support group by year in [investment API service](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/app/portfolio/portfolio.service.ts#L249)
- [ ] Refactor duplicate code (e.g. refactor `getInvestmentsByMonth()` → `getInvestmentsGroupedBy()`)

**Comment by yksolanki9** [comment]
@dtslvr I'd like to take this up. Please assign it to me.
