### ISSUE TITLE
Setup prisma-json-types-generator

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#2445]
With the [Prisma Json Types Generator](https://github.com/arthurfiorette/prisma-json-types-generator), [json types](https://github.com/ghostfolio/ghostfolio/blob/main/prisma/schema.prisma#L139) should be generated into the ones specified.

### Current implementation

```
const scraperConfiguration = symbolProfile.scraperConfiguration as Prisma.JsonObject;

...

return {
   defaultMarketPrice: scraperConfiguration.defaultMarketPrice as number,
   headers: scraperConfiguration.headers as ScraperConfiguration['headers'],
   selector: scraperConfiguration.selector as string,
   url: scraperConfiguration.url as string
}
```
`scraperConfiguration` needs to be casted heavily in the [SymbolProfileService](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/services/symbol-profile/symbol-profile.service.ts#L193).

### New implementation

```
const scraperConfiguration = symbolProfile.scraperConfiguration;
```
`scraperConfiguration` should automatically have the type `ScraperConfiguration` from `@prisma/client`.

### Todo

- [ ] Build on top of the existing PR with the initial setup (#2218)
- [ ] Find solution for `ERROR in ./apps/api/src/json-types.ts:1:9 TS2669: Augmentations for the global scope can only be directly nested in external modules or ambient module declarations.`
- [ ] Eliminate [ScraperConfiguration](https://github.com/ghostfolio/ghostfolio/blob/main/libs/common/src/lib/interfaces/scraper-configuration.interface.ts) interface
