### ISSUE TITLE
Add endpoint to transfer cash between accounts

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#2446]
This is a follow up task of #2432.

### Todo

- [ ] Create endpoint `POST api/v1/account/transfer-balance` using `TransferBalanceDto`
- [ ] Add logic which calls [updateAccountBalance()](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/app/account/account.service.ts#L217) for both affected accounts 
- [ ] Enable transfer button [here](https://github.com/ghostfolio/ghostfolio/blob/main/apps/client/src/app/components/accounts-table/accounts-table.component.html#L1)
- [ ] Call endpoint on submit from client

**Comment by Dhoni77** [comment]
Hi @dtslvr can you assign this task to me.
Thanks

**Comment by dtslvr** [comment]
> can you assign this task to me.

Sure 😃
