### ISSUE TITLE
Extend account detail dialog by cash balances

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#2491]
Extend the [AccountDetailDialog](https://github.com/ghostfolio/ghostfolio/tree/main/apps/client/src/app/components/account-detail-dialog) with cash balances.

<img width="1384" alt="account-with-cash-balances" src="https://github.com/ghostfolio/ghostfolio/assets/4159106/4415c7a6-65c5-4959-858b-2f1e5d8e3023">

### Tasks

- [ ] Add [tabs](https://material.angular.io/components/tabs) for _Activities_ (existing) and _Cash Balances_
- [ ] Fetch historical cash balances via `GET api/v1/account/:id/balances` (see [DataService](https://github.com/ghostfolio/ghostfolio/blob/main/apps/client/src/app/services/data.service.ts))
- [ ] Display cash balances in a [data table](https://material.angular.io/components/table) (create a dedicated component `account-balances` in `libs/ui/src/lib`)

Hint: you can easily populate the `AccountBalances` table by updating the _Account Balance_ of an account multiple times.

**Comment by thesanjeevsharma** [comment]
@dtslvr can I work on this?

Also, is there an existing tabs component that I refer to?

**Comment by dtslvr** [comment]
> @dtslvr can I work on this?

Sure! 👍🏻

> Also, is there an existing tabs component that I refer to?

I would use the [official example](https://material.angular.io/components/tabs/examples) from _Angular Material_ as a reference.

**Comment by thesanjeevsharma** [comment]
<img width="798" alt="Screenshot 2023-10-20 at 2 03 25 AM" src="https://github.com/ghostfolio/ghostfolio/assets/29539278/9f95f25f-1442-4c10-b168-526bc03249bd">

@dtslvr I am not able to create activities. `/symbol` API is failing. Is it just failing for me?

I am getting this in console.
```
ERROR [YahooFinanceService] BadRequestError: Missing required query parameter=symbols
```

**Comment by dtslvr** [comment]
Hi @thesanjeevsharma

Does the problem still persist? Sometimes it occurs only temporarily. I would use something like `AAPL` as a symbol for testing. Hint: for this ticket you don't even need an activity.
