### ISSUE TITLE
Grant private access

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#2820]
Extend the grant access dialog (`CreateOrUpdateAccessDialog`) by supporting private access.

<img width="1132" alt="grant-private-access" src="https://github.com/ghostfolio/ghostfolio/assets/4159106/9f9c52e4-b947-44a3-afd3-848fd322ebec">

### Todo

- [x] Extend the type selector by _Private_ (`PRIVATE`)
- [x] Extend the form by the required input _User ID_ (`granteeUserId`) → visible if type is `PRIVATE`
- [x] Validate if `granteeUserId` corresponds to a `userId` () → show an alert if (`400 Bad request`)

**Comment by x1c0** [comment]
sounds great, lets do it :D
