### ISSUE TITLE
Introduce permissions in access

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#2830]
Extend the grant access dialog (`CreateOrUpdateAccessDialog`) by supporting permissions.

<img width="792" alt="grant-access-with-permission" src="https://github.com/ghostfolio/ghostfolio/assets/4159106/7b7f1562-6070-4430-a600-5797107e1696">

Implement based on https://github.com/ghostfolio/ghostfolio/pull/2833: Run `yarn database:push` to synchronize the new schema with your local database.

### Todo

- [x] Add `permissions` to database model `Access`: `READ` | `READ_RESTRICTED` (Default value: `[READ_RESTRICTED]`) → https://github.com/ghostfolio/ghostfolio/pull/2833
- [x] Add the permission selector to the grant access dialog: _Restricted View_ and _View_
- [x] Display the permissions in the `AccessTableComponent` (_Restricted View_ and _View_)
- [x] Adapt `RedactValuesInResponseInterceptor` that values are only redacted if `permissions` of `Access` include `READ_RESTRICTED` in impersonation mode

**Comment by x1c0** [comment]
lets do it :D

**Comment by dtslvr** [comment]
Closed via #2870.
