### ISSUE TITLE
Reload data on logo click

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#2952]
If the user is on the home page, data of the `HomeOverviewComponent` should be reloaded.

### TODO

- [x] Create `LayoutService` in `apps/client/src/app/core` with `shouldReloadSubject`
- [x] Emit an event from `HeaderComponent` on click on the logo (only on home page, cf. `currentRoute`)
- [x] Subscribe to event in `HomeOverviewComponent` and reload data

**Comment by TobiasXy** [comment]
How about calling the subject `logoClickedSubject` and trigger it uncondtioally when the logo is clicked?
It is less explicit about the currently only usage (reloading the page), but it gets rid of the condition to trigger it only when the path matches.

Since we would only subscribe to it in `HomeOverviewComponent` anyway the effect would be the same.
