### ISSUE TITLE
[Feature] Set up unit test that loads activity from exported json file

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#3807]
To easily set up a unit test, it would be great to support exported activities (`json`). In this issue, such a test should be implemented as a proof of concept.

### Todo

- [ ] Duplicate the test [portfolio-calculator-novn-buy-and-sell.spec.ts](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/app/portfolio/calculator/twr/portfolio-calculator-novn-buy-and-sell.spec.ts)
- [ ] Instead of the hard coded activities, load activities dynamically from the json file [ok-novn-buy-and-sell.json](https://github.com/ghostfolio/ghostfolio/blob/98e9b5d895ba508f79e5a07e0f59157bb94899a4/test/import/ok-novn-buy-and-sell.json)
- [ ] This new test should pass

**Comment by uday-rana** [comment]
Hi, I'd like to work on this.

**Comment by dtslvr** [comment]
> Hi, I'd like to work on this.

I just noticed you're currently assigned to two issues, @uday-rana. To give other developers a chance to participate in [Hacktoberfest 2024](https://ghostfol.io/en/blog/2024/09/hacktoberfest-2024), I’ll unassign you from this one 🙂

**Comment by dhaneshwaritendle** [comment]
> To easily set up a unit test, it would be great to support exported activities (`json`). In this issue, such a test should be implemented as a proof of concept.
> 
> ### Todo
> * [ ]  Duplicate the test [portfolio-calculator-novn-buy-and-sell.spec.ts](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/app/portfolio/calculator/twr/portfolio-calculator-novn-buy-and-sell.spec.ts)
> * [ ]  Instead of the hard coded activities, load activities dynamically from the json file [ok-novn-buy-and-sell.json](https://github.com/ghostfolio/ghostfolio/blob/98e9b5d895ba508f79e5a07e0f59157bb94899a4/test/import/ok-novn-buy-and-sell.json)
> * [ ]  This new test should pass

Hi i would like to work on this issue.

**Comment by dhaneshwaritendle** [comment]
Can I get your feedback regarding this issue [https://github.com/dhaneshwaritendle/ghostfolio/pulls](https://github.com/dhaneshwaritendle/ghostfolio/pulls)? 
I have added the changes in the new branch [Feature](https://github.com/dhaneshwaritendle/ghostfolio/tree/Feature)
I have added the screenshot of the tests running.
![image](https://github.com/user-attachments/assets/2d87fd9c-c6c7-45f8-b449-e609449245ea)
